name: mangs/super-cache-action
author: Eric L. Goldstein
description: Simple GitHub Action that improves cache performance over actions/cache's recommendations for Node.js projects
inputs:
  cache-targets:
    default: ./node_modules
    description: Single- or multi-line string wherein each line targets a resource to cache; can use globs
    required: false
  package-manager:
    default: npm
    description: Package manager target for caching operations
    required: false
outputs:
  cache-hit:
    description: A boolean value indicating if a match was found in the repository's cache
    value: ${{ steps.package-manager-cache.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Capture package manager version number
      id: capture
      run: echo "::set-output name=version-number::$(${{ inputs.package-manager }} --version)"
      shell: bash
    # - name: Capture NPM version number
    #   id: npm-capture
    #   run: echo "::set-output name=version-number::$(${{ inputs.package-manager }} --version)"
    #   shell: bash
    # - if: inputs.package-manager == "pnpm"
    #   name: Capture PNPM version number
    #   id: pnpm-capture
    #   run: echo "::set-output name=version-number::$(pnpm --version)"
    #   shell: bash
    # - if: inputs.package-manager == "yarn"
    #   name: Capture Yarn version number
    #   id: yarn-capture
    #   run: echo "::set-output name=version-number::$(yarn --version)"
    #   shell: bash
    - if: inputs.package-manager == 'npm' || inputs.package-manager == 'pnpm' || inputs.package-manager == 'yarn'
      uses: actions/cache@v3
      id: package-manager-cache
      with:
        path: ${{ inputs.cache-targets }}
        key: ${{ runner.os }}-${{ inputs.package-manager }}-v${{ steps.capture.outputs.version-number }}-${{ hashFiles('./package-lock.json') }}
