name: mangs/dependency-super-cache-action
author: Eric L. Goldstein
description: GitHub Action that is simple and greatly improves dependency cache performance over actions/cache for Node.js projects
inputs:
  dependencies_to_cache:
    default: "./node_modules"
    description: Single- or multi-line string wherein each line targets dependencies to cache; can use globs
    required: false
outputs:
  cache-hit:
    description: A boolean value indicating if a match was found in the repository's cache
    value: ${{ steps.npm-cache.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Capture NPM version number
      id: npm-capture
      run: echo "::set-output name=version-number::$(npm -v)"
      shell: bash
    - uses: actions/cache@v3
      id: npm-cache
      with:
        path: ${{ inputs.dependencies_to_cache }}
        key: ${{ runner.os }}-npm-v${{ steps.npm-capture.outputs.version-number }}-${{ hashFiles('./package-lock.json') }}
