name: Publish Release Notes Workflow
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: mangs/simple-release-notes-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
